// nyc.config.js
module.exports = {
    extends: '@istanbuljs/nyc-config-typescript',
    all: true,
    include: [
        'app/**/*.{ts,tsx}',
        'components/**/*.{ts,tsx}',
        'hooks/**/*.{ts,tsx}',
        'lib/**/*.{ts,tsx}',
        'utils/**/*.{ts,tsx}',
        'services/**/*.{ts,tsx}',
        'store/**/*.{ts,tsx}',
        'pages/**/*.{ts,tsx}',
    ],
    exclude: [
        '**/*.spec.ts',
        '**/*.spec.tsx',
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/*.integration.test.ts',
        '**/*.integration.test.tsx',
        '**/node_modules/**',
        '**/tests/**',
        '**/__tests__/**',
        '**/*.d.ts',
        '**/types/**',
        '**/*.stories.tsx',
        '**/*.stories.ts',
        '**/.next/**',
        '**/dist/**',
        '**/build/**',
        '**/coverage/**',
        '**/*.config.js',
        '**/*.config.ts',
        '**/jest.setup.*',
        '**/jest.config.*',
        '**/playwright.config.*',
        '**/__mocks__/**',
        '**/mocks/**',
        // Covered by their Jest service suites, not the browser E2E suite.
        '**/lib/firestore/productService.ts',
        '**/lib/firestore/triviaService.ts',
    ],
    reporter: ['lcov', 'html', 'text', 'text-summary', 'json', 'json-summary'],
    reportDir: 'coverage/playwright',
    tempDir: '.nyc_output/playwright',
    watermarks: {
        lines: [0, 69],
        functions: [0, 31],
        branches: [0, 31],
        statements: [0, 67]
    },
    // Important for Playwright coverage
    instrument: true,
    sourceMap: true,
    cache: false,
    skipFull: false,
    checkCoverage: true,
    statements: 38,
    branches: 32,
    functions: 30,
    lines: 41,
};
