// lib/firestore/productTypes.ts

export interface User {
    id?: string;
    name: string;
    email: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface Product {
    // Auto-generated by Firestore
    id?: string;

    // Required fields
    name: string;
    price: number;
    inStock: boolean;

    // Optional fields
    description?: string;
    category?: string;
    userId?: string;           // Track who created the product (set by auth)

    // Timestamps (set by serverTimestamp())
    createdAt?: Date | string;
    updatedAt?: Date | string;
}

// Type for creating a new product (all required fields for creation)
export type CreateProductInput = Omit<Product, 'id' | 'createdAt' | 'updatedAt'>;

// Type for updating a product (all fields optional except id)
export type UpdateProductInput = Partial<Omit<Product, 'id' | 'createdAt' | 'updatedAt'>>;

// Add more interfaces as needed for your collections